name: flutter_web
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: any
  google_fonts: ^6.2.1
  supabase_flutter: ^2.5.6
  shared_preferences: ^2.2.2
  google_sign_in: ^6.1.5
  go_router: ^16.0.0
  url_strategy: ^0.3.0
  get_storage: ^2.1.1
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
