# Generated by Django 5.2.4 on 2025-07-07 15:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'Contact',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Order timestamp')),
                ('full_name', models.TextField(blank=True, help_text='Customer full name (First + Last)', null=True)),
                ('email', models.TextField(blank=True, help_text='Customer email address', null=True)),
                ('phone', models.TextField(blank=True, help_text='Customer phone number', null=True)),
                ('address', models.TextField(blank=True, help_text='Complete customer address', null=True)),
                ('item', models.TextField(blank=True, help_text='Items in order (JSON string or comma-separated)', null=True)),
                ('item_quantity', models.TextField(blank=True, help_text='Item quantities (JSON string or comma-separated)', null=True)),
                ('total_price', models.BigIntegerField(blank=True, help_text='Total order price in Rupiah', null=True)),
                ('payment_method', models.TextField(blank=True, help_text='Payment method used', null=True)),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order History',
                'db_table': 'order_history',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SupabaseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
