# Generated by Django 5.2.4 on 2025-07-04 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupabaseProduct',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('category', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('company', models.TextField(blank=True, null=True)),
                ('country', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('zip_code', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.TextField()),
                ('total_amount', models.IntegerField()),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_orders',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='products_cart',
        ),
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='products_favorite',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products_product',
        ),
    ]
