name: flutter_auth_app
description: Flutter app with Django authentication

# Prevent publishing to pub.dev
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.6

  # HTTP requests untuk API calls
  http: ^0.13.6

  # Secure storage untuk tokens
  flutter_secure_storage: ^9.2.2

  # State management
  provider: ^6.1.2

  google_sign_in: ^6.2.1

  # Navigation (optional)
  go_router: ^14.2.7

  # JSON annotation (optional, untuk model classes)
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules
  flutter_lints: ^3.0.2

  # JSON serialization (optional)
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  # Assets (uncomment jika butuh)
  # assets:
  #   - images/
  #   - icons/

  # Fonts (uncomment jika butuh custom fonts)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
